# Generated by Django 4.1.7 on 2023-02-25 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0011_remove_staffdriver_user_remove_staffforeman_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technic',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='technic',
            name='attached_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_driver', to=settings.AUTH_USER_MODEL, verbose_name='Прикрепленный водитель'),
        ),
    ]
