# Generated by Django 4.1.7 on 2023-02-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_technic_supervisor_alter_technic_attached_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtechnic',
            name='var_aptech',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='applicationtoday',
            name='var_aptd',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
