# Generated by Django 4.1.7 on 2023-02-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_applicationtechnic_var_aptech_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloneApplicationTechnic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_original_ap', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='Ид оригинала')),
                ('ID_app_for_day', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='Ид заявки на объект')),
                ('ID_technic_driver', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='Ид техника-водитель')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
                ('priority', models.DecimalField(decimal_places=0, default=1, max_digits=3, verbose_name='Приоритет заявки')),
                ('var_check', models.BooleanField(default=False, verbose_name='Проверена')),
            ],
            options={
                'verbose_name': 'Снимок заявки на технику',
                'verbose_name_plural': 'Снимоки заявки на технику',
            },
        ),
        migrations.AddField(
            model_name='applicationtechnic',
            name='var_check',
            field=models.BooleanField(default=False, verbose_name='Проверена'),
        ),
    ]
