# Generated by Django 4.1.7 on 2023-03-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_rename_meterial_applicationmeterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmeterial',
            name='status_checked',
            field=models.BooleanField(default=False, verbose_name='Проверенна'),
        ),
    ]
