# Generated by Django 4.1 on 2023-12-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMeterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_A_M', models.IntegerField()),
                ('date', models.DateField()),
                ('app_for_day_i', models.IntegerField(verbose_name='Заявка на объект')),
                ('description', models.TextField(blank=True, max_length=2048, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationTechnic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_A_T', models.IntegerField()),
                ('date', models.DateField()),
                ('app_for_day_i', models.IntegerField(verbose_name='Заявка на объект')),
                ('technic_driver_i', models.IntegerField(verbose_name='Техника-Водитель')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
                ('priority', models.DecimalField(decimal_places=0, default=1, max_digits=3, verbose_name='Приоритет заявки')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationToDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_A_T_D', models.IntegerField()),
                ('date', models.DateField()),
                ('construction_site_i', models.IntegerField()),
                ('description', models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='Примечание для объекта')),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_C_S', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=512, null=True, verbose_name='Адрес')),
                ('foreman_i', models.IntegerField(verbose_name='Прораб')),
                ('bd_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_D', models.IntegerField()),
                ('driver_i', models.IntegerField(verbose_name='Водитель')),
                ('status', models.BooleanField(default=True, verbose_name='Статус водителя')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='Technic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_T', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('id_information', models.CharField(max_length=256)),
                ('tech_type', models.CharField(max_length=256)),
                ('designation', models.TextField(blank=True, max_length=1024, null=True)),
                ('attached_driver_i', models.IntegerField(verbose_name='Прикрепленный водитель')),
                ('supervisor_i', models.IntegerField(verbose_name='Руководитель')),
                ('bd_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TTechnicDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_T_D', models.IntegerField()),
                ('technic_i', models.IntegerField(verbose_name='Транспортное средство')),
                ('driver_i', models.IntegerField(verbose_name='Водитель техники')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('status', models.BooleanField(default=True, verbose_name='Статус техники')),
            ],
        ),
        migrations.CreateModel(
            name='TWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_W_D', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_U', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('post', models.CharField(blank=True, max_length=150, null=True)),
                ('date_joined', models.DateTimeField()),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('bd_status', models.BooleanField(default=True)),
            ],
        ),
    ]
