# Generated by Django 4.1 on 2023-12-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructionsite',
            options={'verbose_name': 'Строительный объект', 'verbose_name_plural': 'Строительные объекты'},
        ),
        migrations.AlterModelOptions(
            name='technic',
            options={'verbose_name': 'Единица техники', 'verbose_name_plural': 'Техника'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.RenameField(
            model_name='technic',
            old_name='designation',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='constructionsite',
            name='bd_status',
            field=models.BooleanField(default=False, verbose_name='Удален из базы данных'),
        ),
        migrations.AlterField(
            model_name='constructionsite',
            name='foreman_i',
            field=models.IntegerField(verbose_name='id прораба'),
        ),
        migrations.AlterField(
            model_name='constructionsite',
            name='id_C_S',
            field=models.IntegerField(verbose_name='id объекта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bd_status',
            field=models.BooleanField(default=False, verbose_name='Удален из базы данных'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_U',
            field=models.IntegerField(verbose_name='id user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, verbose_name='Никнейм'),
        ),
    ]
