# Generated by Django 4.1 on 2023-12-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_alter_constructionsite_options_alter_technic_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationmeterial',
            options={'verbose_name': 'Заявка на материал', 'verbose_name_plural': 'Заявки на материалы'},
        ),
        migrations.AlterModelOptions(
            name='applicationtechnic',
            options={'verbose_name': 'Заявка на технику', 'verbose_name_plural': 'Заявки на технику'},
        ),
        migrations.AlterModelOptions(
            name='applicationtoday',
            options={'verbose_name': 'Заявка на объект', 'verbose_name_plural': 'Заявки на объект'},
        ),
        migrations.AlterModelOptions(
            name='tdriver',
            options={'verbose_name': 'Отметка водителя', 'verbose_name_plural': 'Табель | Водители'},
        ),
        migrations.AlterModelOptions(
            name='ttechnicdriver',
            options={'verbose_name': 'Отметка техники', 'verbose_name_plural': 'Табель | Техники'},
        ),
        migrations.AlterModelOptions(
            name='tworkday',
            options={'verbose_name': 'Рабочий день', 'verbose_name_plural': 'Табель | Рабочие дени'},
        ),
        migrations.AlterField(
            model_name='applicationmeterial',
            name='app_for_day_i',
            field=models.IntegerField(verbose_name='id заявки на объект'),
        ),
        migrations.AlterField(
            model_name='applicationmeterial',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='applicationmeterial',
            name='id_A_M',
            field=models.IntegerField(verbose_name='id заявки на материал'),
        ),
        migrations.AlterField(
            model_name='applicationtechnic',
            name='app_for_day_i',
            field=models.IntegerField(verbose_name='id заявки на объект'),
        ),
        migrations.AlterField(
            model_name='applicationtechnic',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='applicationtechnic',
            name='id_A_T',
            field=models.IntegerField(verbose_name='id заявки на технику'),
        ),
        migrations.AlterField(
            model_name='applicationtechnic',
            name='technic_driver_i',
            field=models.IntegerField(verbose_name='id отметки техники'),
        ),
        migrations.AlterField(
            model_name='applicationtoday',
            name='construction_site_i',
            field=models.IntegerField(verbose_name='id объекта'),
        ),
        migrations.AlterField(
            model_name='applicationtoday',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='applicationtoday',
            name='id_A_T_D',
            field=models.IntegerField(verbose_name='id заявки на объект'),
        ),
        migrations.AlterField(
            model_name='tdriver',
            name='driver_i',
            field=models.IntegerField(verbose_name='id водителя'),
        ),
        migrations.AlterField(
            model_name='tdriver',
            name='id_D',
            field=models.IntegerField(verbose_name='id отметки водителя'),
        ),
        migrations.AlterField(
            model_name='technic',
            name='attached_driver_i',
            field=models.IntegerField(blank=True, null=True, verbose_name='id Прикрепленного водителя'),
        ),
        migrations.AlterField(
            model_name='technic',
            name='bd_status',
            field=models.BooleanField(default=False, verbose_name='Удален из базы данных'),
        ),
        migrations.AlterField(
            model_name='technic',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='technic',
            name='id_T',
            field=models.IntegerField(verbose_name='id техники'),
        ),
        migrations.AlterField(
            model_name='technic',
            name='id_information',
            field=models.CharField(max_length=256, verbose_name='Идентификационная информация'),
        ),
        migrations.AlterField(
            model_name='technic',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название техники'),
        ),
        migrations.AlterField(
            model_name='technic',
            name='supervisor_i',
            field=models.IntegerField(verbose_name='id Руководителя'),
        ),
        migrations.AlterField(
            model_name='technic',
            name='tech_type',
            field=models.CharField(max_length=256, verbose_name='Тип техники'),
        ),
        migrations.AlterField(
            model_name='ttechnicdriver',
            name='driver_i',
            field=models.IntegerField(verbose_name='id водителя техники'),
        ),
        migrations.AlterField(
            model_name='ttechnicdriver',
            name='id_T_D',
            field=models.IntegerField(verbose_name='id отметки техники'),
        ),
        migrations.AlterField(
            model_name='ttechnicdriver',
            name='technic_i',
            field=models.IntegerField(verbose_name='id транспортного средства'),
        ),
        migrations.AlterField(
            model_name='tworkday',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='tworkday',
            name='id_W_D',
            field=models.IntegerField(verbose_name='id рабочего дня'),
        ),
        migrations.AlterField(
            model_name='tworkday',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Рабочий день'),
        ),
    ]
