# Generated by Django 4.1 on 2023-12-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_alter_applicationmeterial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionsite',
            name='foreman_i',
            field=models.IntegerField(blank=True, null=True, verbose_name='id прораба'),
        ),
    ]
