# Generated by Django 4.1 on 2023-12-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_alter_constructionsite_foreman_i'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtechnic',
            name='technic_driver_i',
            field=models.IntegerField(blank=True, null=True, verbose_name='id отметки техники'),
        ),
    ]
