# Generated by Django 4.1 on 2023-12-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_alter_applicationtechnic_technic_driver_i'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdriver',
            name='driver_i',
            field=models.IntegerField(blank=True, null=True, verbose_name='id водителя'),
        ),
        migrations.AlterField(
            model_name='technic',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Название техники'),
        ),
        migrations.AlterField(
            model_name='technic',
            name='supervisor_i',
            field=models.IntegerField(blank=True, null=True, verbose_name='id Руководителя'),
        ),
        migrations.AlterField(
            model_name='ttechnicdriver',
            name='driver_i',
            field=models.IntegerField(blank=True, null=True, verbose_name='id водителя техники'),
        ),
        migrations.AlterField(
            model_name='ttechnicdriver',
            name='technic_i',
            field=models.IntegerField(blank=True, null=True, verbose_name='id транспортного средства'),
        ),
    ]
