# Generated by Django 4.1.7 on 2023-02-25 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_technic_attached_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdriver',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staffforeman',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staffmaster',
            name='foreman',
        ),
        migrations.RemoveField(
            model_name='staffmaster',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staffmechanic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staffsupply',
            name='user',
        ),
        migrations.DeleteModel(
            name='StaffAdmin',
        ),
        migrations.DeleteModel(
            name='StaffDriver',
        ),
        migrations.DeleteModel(
            name='StaffForeman',
        ),
        migrations.DeleteModel(
            name='StaffMaster',
        ),
        migrations.DeleteModel(
            name='StaffMechanic',
        ),
        migrations.DeleteModel(
            name='StaffSupply',
        ),
    ]
