# Generated by Django 4.1.7 on 2023-02-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_cloneapplicationtechnic_applicationtechnic_var_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtechnic',
            name='var_ID_orig',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='Ид ApplicationTechnic'),
        ),
    ]
