# Generated by Django 4.1.7 on 2023-03-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_remove_applicationtechnic_var_aptech'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtechnic',
            name='id_group',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='Ид группы'),
        ),
    ]
