# Generated by Django 4.1.7 on 2023-03-02 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_applicationtechnic_id_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
                ('app_for_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.applicationtoday', verbose_name='Заявка на объект')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
    ]
