# Generated by Django 4.1.7 on 2023-03-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_meterial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meterial',
            new_name='ApplicationMeterial',
        ),
    ]
