# Generated by Django 4.1.7 on 2023-03-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_applicationmeterial_status_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
