# Generated by Django 4.1.7 on 2023-03-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_alter_applicationmeterial_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtoday',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Примечание для объекта'),
        ),
    ]
