# Generated by Django 4.1.7 on 2023-03-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_applicationtoday_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoday',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='Примечание для объекта'),
        ),
    ]
